[package]
name = "manis-profile"
description = "Typed Manis profiles and deterministic Mihomo configuration compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = "1.0.229"
serde_json = { version = "1.0.151", features = ["preserve_order"] }
serde-saphyr = "1.2.0"

[lints]
workspace = true
